[project]
name = "outside-the-box"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dd>=0.6.0",
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.1",
    "scipy>=1.16.1",
    "tensorflow>=2.20.0",
]
